server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    access_log /dev/stdout;
    error_log /dev/stderr warn;

    location = /health {
        access_log off;
        default_type text/plain;
        return 200 'OK';
    }

    location = / {
        return 301 /momo-store/;
    }

    location = /momo-store {
        return 301 /momo-store/;
    }

    location /momo-store/ {
        try_files $uri $uri/ /momo-store/index.html;
    }
}
